name: Terraform Plan

on:
  pull_request:

env:
  TERRAFORM_VERSION: "1.7.5"
  TF_IN_AUTOMATION: "True"
  TF_WORKING_DIR: "workload/terraform/jamfpro"
  
jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    if: github.event.review.state != 'approved'
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Get PR ID
        id: pr-id
        shell: bash
        env:
          GITHUB_REF: ${{ inputs.github_ref }}
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Terraform Plan
        uses: ./.github/plan/action.yml
        with:
          terraform_working_directory: ${{ env.TF_WORKING_DIR }}
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_id: ${{ steps.pr-id.outputs.PR_NUMBER }}
          jamfpro_client_secret: ${{ secrets.JAMFPRO_CLIENT_SECRET }}
          jamfpro_client_id: ${{ secrets.JAMFPRO_CLIENT_ID }}
          jamfpro_instance_name: ${{ secrets.JAMFPRO_INSTANCE_NAME }}
          