on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Terraform module
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform validate
        uses: dflook/terraform-validate@v1.42
        id: validate
        with:
          path: workload/terraform/jamfpro

      - name: Validate failed
        if: ${{ failure() && steps.validate.outputs.failure-reason == 'validate-failed' }}
        run: echo "terraform validate failed"